Add check for ZFS pool state
innogames/igmonplugins pull request #216
Opened 2020-10-23 10:46 UTC by TuxPowered42

2020-10-23 11:27 UTC, lamaral requested changes

2020-10-23 11:27 UTC, lamaral commented on src/check_zfs.py
> +class ExitCodes:
Per our Python script coding style, helper classes should be moved to the end, before the `if __name__ == '__main__':` block.

2020-10-23 11:27 UTC, lamaral commented on src/check_zfs.py
> +        ret_code = ExitCodes.critical
Do we really want to go straight critical on all other cases?

Our raid_state check goes to Warning in some cases of degradation.

2020-10-24 10:20 UTC, TheFRedFox requested changes

2020-10-24 10:20 UTC, TheFRedFox commented on src/check_zfs.py
> +            ['/sbin/zpool', 'list', '-H'],stderr=STDOUT,
```suggestion
            ['/sbin/zpool', 'list', '-H'], stderr=STDOUT
```

2020-10-24 10:20 UTC, TheFRedFox commented on src/check_zfs.py
> +        exit_header = 'No zpools found!'
Early return can be used here:

```suggestion
    if not lines:
        print('No zpools found!')
        return ExitCodes.unknown
    
    exit_code = ExitCodes.ok
    exit_header = 'All zpools are fine'
    for line in lines:
        zpool_code, zpool_name, zpool_state = parse_line(line)
        exit_multiline.append('{}: {}'.format(zpool_name, zpool_state))
        if zpool_code > exit_code:
            exit_code = zpool_code
            exit_header = 'Some zpools are not online!'
```

2020-10-24 10:20 UTC, TheFRedFox commented on src/check_zfs.py
> +
Seems to be an unneeded extra line
```suggestion
```

2020-10-24 10:20 UTC, TheFRedFox commented on src/check_zfs.py
> +from sys import exit
Like that the builtin `exit` function will be shadowed. For that we might rather just want to import `sys` and use `sys.exit`.

2020-10-24 10:20 UTC, TheFRedFox commented on src/check_zfs.py
> +    exit(main())
It's actually not dumb to do it like that. ^^

2020-10-24 10:20 UTC, TheFRedFox commented on src/check_zfs.py
> +    tank_130T_75.9T_54.1T_-_22%_58%_1.00x_ONLINE_-
:+1: for the tabs you could also just write it `tank<\tr>130T` so it should be self explaining. But nothing to do, it's good like that already. ;)

2020-10-24 10:20 UTC, TheFRedFox commented on src/check_zfs.py
> +    line_split = line.split('\t')
It could also possible like that (if it fits with the line limit):
```suggestion
    name, _, _, _, _, _, _, _, code = line.split('\t')
```
`name` would hold `line_split[0]` then and `code` `line_split[8]`. `_` would hold the last occurrence, so `line_split[7]`

Both is fine for me here, you can choose.

2020-10-24 10:20 UTC, TheFRedFox commented on src/check_zfs.py
> +class ExitCodes:
👍

2020-10-26 15:22 UTC, TuxPowered42 commented on src/check_zfs.py
> +class ExitCodes:
Fixed.

2020-10-26 15:30 UTC, TuxPowered42 commented on src/check_zfs.py
> +
Fixed.

2020-10-26 15:49 UTC, lamaral approved these changes

2020-10-26 17:27 UTC, TheFRedFox approved these changes
Just 1 `return(..)` with braces and 1 thing which I would change. Will give it an early approve already though.

2020-10-26 17:27 UTC, TheFRedFox commented on src/check_zfs.py
> +        return(ExitCodes.unknown)
```suggestion
        return ExitCodes.unknown
```

2020-10-26 17:27 UTC, TheFRedFox commented on src/check_zfs.py
> +    return (ret_code, name, "health: {}, fragmentation: {}%, capacity: {}%".format(health, frag, cap))
By separating this it's easier to read and understand for me.
```suggestion

    message = 'health: {}, fragmentation: {}%, capacity: {}%'
    return (ret_code, name, message.format(health, frag, cap))
```

2020-10-26 17:27 UTC, TheFRedFox commented on src/check_zfs.py
> +    return (ret_code, name, "health: {}, fragmentation: {}%, capacity: {}%".format(health, frag, cap))
Looks like single quotes should rather be used.
```suggestion

    return (ret_code, name, 'health: {}, fragmentation: {}%, capacity: {}%'.format(health, frag, cap))
```

2020-10-27 08:21 UTC, kofrezo approved these changes

2020-10-27 08:21 UTC, kofrezo commented on src/check_zfs.py
> +    name, _, _, _, _, frag, cap, _, health, _ = line.split('\t')
```suggestion
    status = line.split('\t')
    name, frag, cap, health = status[0], status[5], status[6], status[8]
```

2020-10-27 09:18 UTC, TuxPowered42 commented on src/check_zfs.py
> +    name, _, _, _, _, frag, cap, _, health, _ = line.split('\t')
I've done it the way @TheFRedFox suggested. Which one is more pythonic?

2020-10-27 09:20 UTC, TuxPowered42 commented on src/check_zfs.py
> +    return (ret_code, name, "health: {}, fragmentation: {}%, capacity: {}%".format(health, frag, cap))
Fixed.

2020-10-27 09:20 UTC, TuxPowered42 commented on src/check_zfs.py
> +    return (ret_code, name, "health: {}, fragmentation: {}%, capacity: {}%".format(health, frag, cap))
Fixed.

2020-10-27 09:21 UTC, TuxPowered42 commented on src/check_zfs.py
> +        return(ExitCodes.unknown)
Fixed.

2020-10-27 09:22 UTC, TuxPowered42 commented on src/check_zfs.py
> +    name, _, _, _, _, frag, cap, _, health, _ = line.split('\t')
I've used a table before and @TheFRedFox asked me to change it to this format with `_`. Which is more pythonic?

2020-10-27 11:48 UTC, TheFRedFox commented on src/check_zfs.py
> +    name, _, _, _, _, frag, cap, _, health, _ = line.split('\t')
I would say mine and @kofrezo's is more pythonic than your original one. Now, I guess, it is more about readability, for which I find @kofrezo's actually even more readable than mine.

2020-10-27 13:59 UTC, TuxPowered42 commented on src/check_zfs.py
> +    name, _, _, _, _, frag, cap, _, health, _ = line.split('\t')
I see one advantage of the current code: if the number of columns changes, the code will crash, no matter if we're using those columns or not. Which is good, becasue that allows us to easily spot modified output of zfs command.

2020-10-27 15:23 UTC, kofrezo commented on src/check_zfs.py
> +    name, _, _, _, _, frag, cap, _, health, _ = line.split('\t')
As @TheFRedFox pointed out my point was to increase readability. 

Yes, your way would cover if the amount of columns changes but also not if the ordering or format changes so if you really want validation I think this should be a dedicated step. 

If you want to cover the length you could additionally add a assert statement. This would not break with a cryptic error message such as "Too many values to unpack" or "Too few values to unpack" but rather make clear what you expect.

```
assert len(data) == 9, "Expected 9 columns from zfs pool list command"
```

2020-10-29 12:30 UTC, TuxPowered42 commented on src/check_zfs.py
> +    name, _, _, _, _, frag, cap, _, health, _ = line.split('\t')
How abouta now?

2020-10-29 12:32 UTC, kofrezo commented on src/check_zfs.py
> +    name, _, _, _, _, frag, cap, _, health, _ = line.split('\t')
I think it is good this way :+1:

2020-10-29 13:26 UTC, merged