libvirt_hosts: Use also Serveradmin data
innogames/igmonplugins pull request #219
Opened 2021-01-06 16:42 UTC by lamaral

2021-01-06 16:53 UTC, TuxPowered42 requested changes

2021-01-06 16:53 UTC, TuxPowered42 commented on src/check_libvirt_hosts.py
> +    vms = [vm.copy() for vm in vms]
If you feel like materializing the query, you can do `vms = list(vms)`

2021-01-06 16:53 UTC, TuxPowered42 commented on src/check_libvirt_hosts.py
> +        print('Duplicated domain defined')
It does not say which domain is duplicated.

2021-01-06 16:53 UTC, TuxPowered42 commented on src/check_libvirt_hosts.py
> +        print('Running VM not associated to the hypervisor in serveradmin')
It does not say which domain is not associated in Serveradmin. Also any multiple-running VM could be easily found by just removing every found VM from the list of VMs from Serveradmin.

2021-01-06 16:53 UTC, TuxPowered42 commented on src/check_libvirt_hosts.py
> +        print('VM associated in serveradmin not running on this HV')
It does not say which VM.

2021-01-06 16:53 UTC, TuxPowered42 commented on src/check_libvirt_hosts.py
> +        ['hostname', 'state']
Is object_id always given to us?

2021-01-06 16:53 UTC, TuxPowered42 commented on src/check_libvirt_hosts.py
> +            name, reason_names.get(state, "unknown").get(reason, "unknown")
The reason/state of VMs is not really human-readible. It could be better described as "running as defined in Serveradmin", "not running as defined in Serveradmin because of retired state", "running even though not defined in Serveradmin" and so on, maybe with some shorter forms.

2021-01-06 16:55 UTC, lamaral commented on src/check_libvirt_hosts.py
> +        print('Duplicated domain defined')
Keep in mind it's heavy WIP. There is a TODO to make it proper :)

2021-01-06 16:56 UTC, lamaral commented on src/check_libvirt_hosts.py
> +        print('VM associated in serveradmin not running on this HV')
Keep in mind it's heavy WIP. There is a TODO to make it proper :)

2021-01-06 16:56 UTC, lamaral commented on src/check_libvirt_hosts.py
> +        ['hostname', 'state']
Yes, it's always given, but I'll make it explicit to be on the safe side.

2021-01-06 16:58 UTC, lamaral commented on src/check_libvirt_hosts.py
> +            name, reason_names.get(state, "unknown").get(reason, "unknown")
This part is leftover. It will get redone.

2021-01-07 13:38 UTC, lamaral commented on src/check_libvirt_hosts.py
> +    vms = [vm.copy() for vm in vms]
Doing like that, would result in a list of DatasetObjects. 
This way, I get a list of dictionaries, containing the DatasetObject data.

2021-01-07 13:39 UTC, lamaral commented on src/check_libvirt_hosts.py
> +        print('Running VM not associated to the hypervisor in serveradmin')
This is fixed in the newer version.

2021-09-07 12:14 UTC, lamaral commented
I'm closing this PR as this functionality will be covered by  the new IGVM consistency check.

2021-09-14 08:45 UTC, lamaral commented
It's reopened as we preferred to go with the simpler solution implemented here.

2024-01-31 10:04 UTC, merged