WIP: Split LBPool check logic from LBPool data export
innogames/igmonplugins pull request #224
Opened 2021-04-27 18:22 UTC by lamaral

2021-04-28 08:27 UTC, TuxPowered42 requested changes

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_export.py
> +    with \
Does `with` work with `(…)`? That would look better IMO.

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_export.py
> +            except redis.exceptions.AuthenticationError:
There's no reason to catch it, if sending to Redis is impossible, there is no way to recover. Maybe unless the error message is totally unreadible to user.

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_export.py
> +        if args.redis_servers:
What if redis servers are not given?

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_export.py
> +                first_lbnode['route_network'] in carps_states
This is 8 spaces, not 4.

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_export.py
> +                'Skipping LB Pool {} because carp is not master {}'.format(
Let's switch to modern Python `f'{var}'` formatting while we are at it.

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_export.py
> +        r = redis.Redis(host=server, port=6379, db=0, password=redis_password)
What if sending to one of servers fail? An exception thrown here will stop data from being sent to the other one. Is there any timeout for those operations? The cron job is supposed to run every minute, there are multiple servers to send data to, it would be unwise to just hang on one server. Is there a way to send in parallel, using modern Python async io?

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_nodes.py
> +        '-n', dest='lbpool_name', required=True,
Is this script run on Nagios server? Then the LB Pool checked is the "host" checked by Nagios. So `-H` should be the LB Pool.

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_nodes.py
> +        hwlb_group = pool_v.get('hwlb_group', None)
Do we expect this key missing in incoming data? I thought the dict is well defined and if yes, then it's safe to crash when keys are missing.

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_nodes.py
> +        min_nodes = pool_v.get('min_nodes', None)
Do we expect this key missing in incoming data? I thought the dict is well defined and if yes, then it's safe to crash when keys are missing.

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_nodes.py
> +        max_nodes = pool_v.get('max_nodes', None)
Do we expect this key missing in incoming data? I thought the dict is well defined and if yes, then it's safe to crash when keys are missing.

2021-04-28 08:27 UTC, TuxPowered42 commented on src/lbpool_nodes.py
> +        alive_nodes = pool_v.get('alive_nodes', 0)
Do we expect this key missing in incoming data? I thought the dict is well defined and if yes, then it's safe to crash when keys are missing.

2021-04-28 08:34 UTC, lamaral commented on src/lbpool_export.py
> +    with \
Sadly doesn't, I tried

2021-04-28 08:35 UTC, lamaral commented on src/lbpool_export.py
> +        if args.redis_servers:
Then the script doesn't run. This argument is required, see line 34.

2021-04-28 08:36 UTC, lamaral commented on src/lbpool_export.py
> +                'Skipping LB Pool {} because carp is not master {}'.format(
Argh, forgot to change from the old script. Will adjust.

2021-04-28 08:37 UTC, lamaral commented on src/lbpool_nodes.py
> +        '-n', dest='lbpool_name', required=True,
Yes. 
Actually makes sense, I'll adjust it.

2021-04-28 08:39 UTC, lamaral commented on src/lbpool_export.py
> +            except redis.exceptions.AuthenticationError:
The message is actually quite clear. I'll remove the try catch.

2021-04-28 08:45 UTC, lamaral commented on src/lbpool_export.py
> +                first_lbnode['route_network'] in carps_states
It's aligned to the parentheses because of pyCharm.

2021-04-28 08:55 UTC, lamaral commented on src/lbpool_nodes.py
> +        '-n', dest='lbpool_name', required=True,
I have updated it to be `-s` and `-H`

2021-04-28 08:58 UTC, lamaral commented on src/lbpool_nodes.py
> +        hwlb_group = pool_v.get('hwlb_group', None)
Yes, export has a well defined dict, so we can clean this up.

2021-04-28 08:58 UTC, lamaral commented on src/lbpool_nodes.py
> +        min_nodes = pool_v.get('min_nodes', None)
Yes, export has a well defined dict, so we can clean this up.

2021-04-28 08:59 UTC, lamaral commented on src/lbpool_nodes.py
> +        max_nodes = pool_v.get('max_nodes', None)
Yes, export has a well defined dict, so we can clean this up.

2021-04-28 08:59 UTC, lamaral commented on src/lbpool_nodes.py
> +        alive_nodes = pool_v.get('alive_nodes', 0)
Yes, export has a well defined dict, so we can clean this up.

2021-04-28 09:42 UTC, lamaral commented on src/lbpool_export.py
> +        r = redis.Redis(host=server, port=6379, db=0, password=redis_password)
I think setting proper timeouts could mitigate the issue.
Implementing asyncio might be a little bit of overhead for shipping data to two redis servers.

2021-04-28 10:37 UTC, lamaral commented on src/lbpool_export.py
> +        r = redis.Redis(host=server, port=6379, db=0, password=redis_password)
I just pushed some changes to address this. 

I'm now setting up proper connect timeouts as well as wrapping each redis connection on a try catch, so we can skip failed ones.

2021-04-28 10:47 UTC, TuxPowered42 commented on src/lbpool_export.py
> +        if args.redis_servers:
If it is always given, there is no need to check it.

2021-04-28 12:36 UTC, lamaral commented on src/lbpool_export.py
> +        if args.redis_servers:
This is outdated, I removed it already.

2021-04-29 13:10 UTC, TuxPowered42 approved these changes

2021-04-29 15:12 UTC, merged