Add check for huge pages
innogames/igmonplugins pull request #243
Opened 2022-01-13 14:54 UTC by meikomeik

2022-01-14 12:22 UTC, lamaral requested changes

2022-01-14 12:22 UTC, lamaral commented on src/check_huge_pages.py
> +                        help='The amout of huge pages to expect')
Please make the argument required, as the script can't run without it.

2022-01-14 12:22 UTC, lamaral commented on src/check_huge_pages.py
> +            f"/proc/meminfo['HugePages_Total'] == {meminfo_huge_pages} "
Please prefix the output with `CRITICAL - `.

2022-01-14 12:22 UTC, lamaral commented on src/check_huge_pages.py
> +            f"/proc/meminfo['HugePages_Total'] is {meminfo_huge_pages} "
Please prefix the output with `OK - `.

2022-01-14 12:22 UTC, lamaral commented on src/check_huge_pages.py
> +            f"which is smaller than {args.value}"
Please make this line consistent with line 56 below.

2022-01-14 12:22 UTC, lamaral commented on src/check_huge_pages.py
> +            f"which is >= {args.value}"
Please make this line consistent with line 50 above.

2022-01-14 12:22 UTC, lamaral commented on src/check_huge_pages.py
> +                        help='The amout of huge pages to expect')
I would also go as far as saying let's make this `--min_value`, so if we ever decide to check for max value, we don't have to change the script calls.

2022-01-14 12:22 UTC, lamaral commented on src/check_huge_pages.py
> +                        help='The amout of huge pages to expect')
Also a typo in `amount`

2022-01-14 12:33 UTC, TheFRedFox commented on src/check_huge_pages.py
> +                        help='The amout of huge pages to expect')
```suggestion
                        help='The amount of huge pages to expect')
```

2022-01-14 12:33 UTC, TheFRedFox commented on src/check_huge_pages.py
> +    parser.add_argument('--value',
If there is no default, but based on the script it looks like a required argument, maybe it should be a positional parameter then? At least it should be configured as required.

2022-01-14 12:33 UTC, TheFRedFox commented on src/check_huge_pages.py
> +    if int(meminfo_huge_pages) < int(args.value):
If `args.value` is of type `int` a cast is not needed anymore.

2022-01-14 12:33 UTC, TheFRedFox commented on src/check_huge_pages.py
> +        return None
Outside you are interpreting `None` return as parsing error. However, a `ValueError` should also then get caught here. `int(value)` and also the `name, value = line.[...].split(':', 1)` could raise a `ValueError` here.

2022-01-14 12:33 UTC, TheFRedFox commented on src/check_huge_pages.py
> +    parser.add_argument('--value',
Also, shouldn't it be of type `int`?

2022-01-14 12:33 UTC, TheFRedFox commented on src/check_huge_pages.py
> +            f"/proc/meminfo['HugePages_Total'] == {meminfo_huge_pages} "
Prefixes like already Luiz said.

2022-01-14 12:58 UTC, meikomeik commented on src/check_huge_pages.py
> +            f"/proc/meminfo['HugePages_Total'] is {meminfo_huge_pages} "
prefixed

2022-01-14 13:02 UTC, meikomeik commented on src/check_huge_pages.py
> +                        help='The amout of huge pages to expect')
Added your suggestions

2022-01-14 13:03 UTC, meikomeik commented on src/check_huge_pages.py
> +            f"/proc/meminfo['HugePages_Total'] == {meminfo_huge_pages} "
Added prefix

2022-01-14 13:03 UTC, meikomeik commented on src/check_huge_pages.py
> +            f"which is smaller than {args.value}"
Should be consistent now

2022-01-14 13:03 UTC, meikomeik commented on src/check_huge_pages.py
> +            f"which is >= {args.value}"
Should be consistent now

2022-01-14 13:03 UTC, meikomeik commented on src/check_huge_pages.py
> +                        help='The amout of huge pages to expect')
fixed typo

2022-01-14 13:05 UTC, meikomeik commented on src/check_huge_pages.py
> +    if int(meminfo_huge_pages) < int(args.value):
Removed not needed int

2022-01-14 13:05 UTC, meikomeik commented on src/check_huge_pages.py
> +    parser.add_argument('--value',
changed it to int

2022-01-14 13:05 UTC, meikomeik commented on src/check_huge_pages.py
> +            f"/proc/meminfo['HugePages_Total'] == {meminfo_huge_pages} "
Done

2022-01-14 13:10 UTC, meikomeik commented on src/check_huge_pages.py
> +        return None
Added ValueError as part of the possible errors though each line always contains a colon folowed by a number so it should never throw a ValueError I think. Anyhow, why not also add ValueError

2022-01-14 13:15 UTC, meikomeik commented on src/check_huge_pages.py
> +    parser.add_argument('--value',
Made the argument required

2022-01-14 15:07 UTC, lamaral approved these changes
There is just one more thing that I didn't see before. 
I'm pre-approving. Feel free to merge after fixing this last comment.

2022-01-14 15:07 UTC, lamaral commented on src/check_huge_pages.py
> +        print('Could not parse /proc/meminfo')
I missed the `UNKNOWN - ` prefix here.

2022-01-17 09:30 UTC, meikomeik commented on src/check_huge_pages.py
> +        print('Could not parse /proc/meminfo')
fixed this one as well

2022-01-17 09:31 UTC, merged