Add script to check event limits for sentry.io teams
innogames/igmonplugins pull request #249
Opened 2022-04-06 16:09 UTC by raimund-s

To test this script you need to obtain a sentry.io api key and organizaiton

2022-04-06 17:24 UTC, TheFRedFox requested changes
Thx for the new script. :)
Unfortunately, it does not follow our Python Scripts Structure Guide. There are also some typos and outdated python usages, which I highlighted. The overall code complexity in the `main` function is also quite high. For me the WTFPM is too high here, so that we should reduce the code complexity there.
So, have fun with the first review iteration. ;)

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +            '''Check if this team is over the team limit'''
These are comments and should not be python docstrings:
```suggestion
            # Check if this team is over the team limit
```

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                                (dsn['rateLimit']['window']))
Is it needed to catch division by zero here?

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                    team['summed_events'] = None
When we are here, can't we break out of the for loop already?

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                                (dsn['rateLimit']['window']))
What is the reason to try to squeeze everything in one line:
```suggestion
                        rate_count = dsn['rateLimit']['count']
                        rate_window = dsn['rateLimit']['window']
                        rate_sum = int(rate_count * 60 / rate_window)
                        team['summed_events'] += rate_sum
```
Would make it much more readable.

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                print('WARNING: {} are configure of {} allowed for team: {}\
```suggestion
                print('WARNING: {} are configured, but {} are allowed for team: {}\
```

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                    '.format(team['summed_events'], args.perteamlimit,
The backslash is not needed:
```suggestion
                print('WARNING: {} are configure of {} allowed for team: {}'
                      .format(team['summed_events'], args.perteamlimit,
```

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                    '.format(team['name']))
Uppercase after colon and backslash is not needed:

```suggestion
                print('WARNING: Unlimited events configured for team: {}'
                      .format(team['name']))
```

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +        print('WARNING: unlimited events configured in total')
Uppercase after colon:
```suggestion
        print('WARNING: Unlimited events configured in total')
```

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +               a the exit code 1, for nrpe compatibility')
```suggestion
               help='If the total amount if events per minute is higher '
               'than this limit the script will exit with a warning and '
               'a the exit code 1, for nrpe compatibility')
```

2022-04-06 17:24 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +    '''Filter teams if list is provided'''
Comments are always appreciated. :)

2022-04-06 17:26 UTC, kofrezo requested changes
@TheFRedFox was faster. I'll just submit what I have so far.

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +import requests
Is it feasible to work without requests but use built-in urllib to keep dependencies to a minimum ?

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +p.add_argument('-b', '--bearer', type=str, required=True, dest='bearer',
FYI: Required arguments are usually positional arguments.

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +p.add_argument('-b', '--bearer', type=str, required=True, dest='bearer',
FYI: The `dest` is implicit too. It defaults to the name (2nd Argument)

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +
Please add the license and a description/purpose here.

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +p.add_argument('-g', '--globallimt', type=int, dest='globallimit',
`--global-limit` (dash as separator) is best practise.

Mind the typo.

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +               a the exit code 1, for nrpe compatibility')
Extra `a`

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +               help='If any teams\' projects\' keys summed up limits is \
When having apostrophes it is best practise to use double quotes for the string

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +    '''Return a list of all teams in the account'''
Use double quotes for doc strings (convention)

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +    headers = {'Authorization': 'Bearer  {}'.format(bearer)}
```suggestion
    headers = {'Authorization': f'Bearer  {bearer}'}
```
With Python 3.7 we can use the more readable f-string format :-)

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +    r = requests.get('https://sentry.io/api/0/organizations/{}/teams/'.format(
Is it worth to make the URL configurable (argparse) and default to this ?

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +def get_teams(organization, bearer):
```suggestion
def get_teams(organization: str, bearer: str) -> str:
```

We can already use type hints :-)

2022-04-06 17:26 UTC, kofrezo commented on src/check_sentryio_limits.py
> +    r = requests.get('https://sentry.io/api/0/projects/{}/{}/keys/'.format(
See comment about URL in get_teams.

Surely we can have a central string for the domain and concatenate the URL

E.g.: `API_URL = 'https://sentry.io/api'`

2022-04-06 19:22 UTC, raimund-s commented on src/check_sentryio_limits.py
> +#!/usr/bin/env python3
done

2022-04-06 19:25 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                    '.format(team['summed_events'], args.perteamlimit,
done

2022-04-06 19:27 UTC, raimund-s commented on src/check_sentryio_limits.py
> +import requests
not sure, urllib seems kind of a hassle compared to requests, only used the urllib2 interface which was kind of a mess compared to request

2022-04-06 19:28 UTC, raimund-s commented on src/check_sentryio_limits.py
> +p.add_argument('-g', '--globallimt', type=int, dest='globallimit',
fixed

2022-04-06 19:28 UTC, raimund-s commented on src/check_sentryio_limits.py
> +               a the exit code 1, for nrpe compatibility')
done

2022-04-06 19:28 UTC, raimund-s commented on src/check_sentryio_limits.py
> +               help='If any teams\' projects\' keys summed up limits is \
changed

2022-04-06 19:28 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    headers = {'Authorization': 'Bearer  {}'.format(bearer)}
changed

2022-04-06 19:29 UTC, raimund-s commented on src/check_sentryio_limits.py
> +def get_teams(organization, bearer):
do these work with builtins or do I need another module for these?

2022-04-06 19:30 UTC, raimund-s commented on src/check_sentryio_limits.py
> +
done

2022-04-06 19:32 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    '''Filter teams if list is provided'''
clarified it

2022-04-06 19:42 UTC, raimund-s commented on src/check_sentryio_limits.py
> +p = ArgumentParser()
moved

2022-04-06 19:42 UTC, raimund-s commented on src/check_sentryio_limits.py
> +def main():
changed

2022-04-06 19:44 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    r = requests.get('https://sentry.io/api/0/organizations/{}/teams/'.format(
done

2022-04-06 19:49 UTC, raimund-s commented on src/check_sentryio_limits.py
> +def get_teams(organization, bearer):
is -> str correct? the return value should be a dict

2022-04-06 19:52 UTC, raimund-s commented on src/check_sentryio_limits.py
> +p.add_argument('-b', '--bearer', type=str, required=True, dest='bearer',
I actually tried to avoid any positional arguments to be more explicit, but I'm not aware of any convention here, then I need to find the correct order of the two :)

2022-04-06 19:53 UTC, kofrezo commented on src/check_sentryio_limits.py
> +def get_teams(organization, bearer):
My bad. No than it should be `dict`

2022-04-06 19:53 UTC, raimund-s commented
Added changes from most of the comments, thank you for all your feedback so far, @TheFRedFox any suggestion on how to split the main logic up properly?

2022-04-06 19:54 UTC, kofrezo commented on src/check_sentryio_limits.py
> +p.add_argument('-b', '--bearer', type=str, required=True, dest='bearer',
I avoided the word convention on purpose. I think both is fine. I see your point. Lets keep it as it is then.

2022-04-06 19:54 UTC, kofrezo commented on src/check_sentryio_limits.py
> +import requests
`requests` it is then. We use it anyway in many other scripts already.

2022-04-06 19:58 UTC, raimund-s commented on src/check_sentryio_limits.py
> +def get_teams(organization, bearer):
added

2022-04-06 19:59 UTC, raimund-s commented on src/check_sentryio_limits.py
> +#!/usr/bin/env python3
done

2022-04-06 20:00 UTC, raimund-s commented on src/check_sentryio_limits.py
> +p.add_argument('-p', '--perteamlimit', type=int, dest='perteamlimit',
done

2022-04-06 20:00 UTC, raimund-s commented on src/check_sentryio_limits.py
> +               warning and the exit code 1')
done

2022-04-06 20:02 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    return(dsns)
canged

2022-04-06 20:02 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    '''Retun a list of DSNs for the project'''
done

2022-04-06 20:02 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    return(teams)
done

2022-04-06 20:03 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    r = requests.get('https://sentry.io/api/0/projects/{}/{}/keys/'.format(
changed

2022-04-06 20:05 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    '''Set exit code and global event counter'''
changed

2022-04-06 20:05 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    '''Iterate over teams, their projects and sum up their keys' rates'''
done

2022-04-06 20:05 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    '''Filter teams if list is provided'''
done

2022-04-06 20:06 UTC, raimund-s commented on src/check_sentryio_limits.py
> +        organization, project), headers=headers)
broke out the api url it's not to readable now in both cases

2022-04-06 20:08 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                args.organization, project['slug'], args.bearer)
I guess about 10 teams with 5-10 projects each, which need get checked for the api keys, this only needs to run once a day or so after the setup is done

2022-04-06 20:12 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                    if type(events) is int:
I get a None in the dict from sentry if there is no rate limit set, if this is the case we always fail unless we just use the script with -v to get the limits but not check against any 

I need one global counter which should be a non-numeric value if any project has no limit set, otherwise it should be the sum of all the limits
The second counter needed is one per team for all the teams projects which should also be none if any project is limitless, otherwise the sum

2022-04-06 20:13 UTC, raimund-s commented on src/check_sentryio_limits.py
> +        exit = -1
fixed, this was a typo, should have been 1

2022-04-06 20:15 UTC, raimund-s commented on src/check_sentryio_limits.py
> +        print('OK: no global event limit')
no we can either check for only the team limits, only the global or the combination, only when neither team nor global limit is to be checked the script will exit 0 in any case an just print the results if -v is used to get an overview about all projects and their limits

2022-04-06 20:17 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                    if type(events) is int:
Is there an infinit int which is always bigger than any other and can be added to? Then I can get rid of these type checks

2022-04-06 20:33 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                    if type(events) is int:
I split the check for unlimited out into a separate variable to make it more readable

2022-04-07 07:42 UTC, raimund-s commented on src/check_sentryio_limits.py
> +        teams = filtered_teams
changed and tested

2022-04-07 07:47 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                args.organization, project['slug'], args.bearer)
I took another look at the api but could not find any other way to retrieve the limits for all dsns other then query each project separately. I might need to slow down the script if we run into an api rate limit here at some point on the sentry side.

2022-04-07 07:49 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                    if type(events) is int:
probably not needed anymore with the unlimited_events bools added now

2022-04-07 09:28 UTC, raimund-s commented on src/check_sentryio_limits.py
> +        print('OK: no global event limit')
I renamed the global limit to organisation limit to avoid the term global in the script

2022-04-07 09:33 UTC, raimund-s commented
@TheFRedFox could you take another look at the man function, I'm not getting around the 3 level nesting but could split it to some degree to make it more readable. 
For the indentation level the 5th is now verbose mode printing only, do you think it is worth it to use a separate function to avoid that?

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                     in args.teams, teams))
You could try this style, which IMO is more readable:
``` python
        teams = list(filter(
            lambda t: t['slug'] in args.teams or t['name'] in args.teams,
            teams
        ))
```
or
``` python
        teams = list(
            filter(
                lambda t: t['slug'] in args.teams or t['name'] in args.teams,
                teams
            )
        )
```

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                   dest='organizationlimit', help='If the total amount of '
What is the reason, that you are not going with the default snake_casing? Which would also be the convention in python to break down compound words.

Would it be possible to get back to the default snake_casing?

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +    # Set exit code and organnization wide event counter
`organization`
btw.
are we going for British or American English? As American English would be `organisation`.

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +    organization = {'summed_events': 0, 'unlimited_events': False}
Variable name is misleading, as it does hold any information about the organisation itself, but rather event.
Would it be possible to name the variable `event_data` or the like?

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +    organization = {'summed_events': 0, 'unlimited_events': False}
Like the idea to store it like that definitely more. 👍🏼

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +            print(f"\nTeam \"{team['name']}\", checking for projects")
What's the reason that you start with a new line here?

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
>          teams = list(filter(lambda t: t['slug'] in args.teams or t['name']
Just general feedback to that commit as reviewer role:
That's too many changes around the whole space, so, will skip that commit and will check the new structure on the big change overview.

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                      .format(team['slug']))
As you are already using the `f-string`-format:
``` python
print(f'WARNING: ...: {team[slug]}')
```
is possible to use.

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +import requests
Just to put my 2 cents here too:
I also think that `requests` is such a highly used and spread module, that we can freely use it here. :)

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +def args_parse():
For almost all scripts we have we go for the function name `parse_args`. No blocker, but if you have the time, change it, so we are consistent throughout the scripts. ^^

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                    print(f"  Key: \"{dsn['name']}\",", end=" ")
```suggestion
                    print(f'  Key: "{dsn["name"]}",', end=' ')
```

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                    print(f"  Key: \"{dsn['name']}\",", end=" ")
What's the reason that it starts with whitespaces here?

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                        print(f'limited to {epm} events per mintue')
```suggestion
                        print(f'limited to {epm} events per minute')
```

2022-04-07 12:59 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                        print('with unlimited events')
The whole printing process here is quite confusing. If it works, it works right now, I would say. In general I would highly question if we can't refactor it to first build the message string and then print it out completely. Or have different message templates to choose from at the end.

2022-04-07 14:46 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                args.organization, project['slug'], args.bearer)
My idea would be to go with concurrent requests. Which would need quite a rewrite of the script, so nothing for now. With 10 * 10 teams and projects we will make 100 requests, which calculation with 1 sec per request we will end up in 100 seconds per run. So not even 2 minutes. Totally fair enough for a daily run.
Just that we have in mind that this will definitely be a bottleneck candidate while scaling.
Might be interesting to put a comment, maybe even a TODO comment, somewhere in the script to make that clear and easy for a future maintainer to directly jump to it.

2022-04-07 14:50 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                    team['summed_events'] = None
With the newest changes it is clear that it is not possible. Therefore: Resolved.

2022-04-08 12:15 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                args.organization, project['slug'], args.bearer)
added

2022-04-08 12:16 UTC, raimund-s commented on src/check_sentryio_limits.py
> +        print('UKNOWN Contidion this shoud not happen')
gone

2022-04-08 12:17 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                                (dsn['rateLimit']['window']))
not for any expected case window will be 60, 300, 3600 ... if there is no rate limit there is neither count nor window

2022-04-08 12:18 UTC, raimund-s commented on src/check_sentryio_limits.py
> +            '''Check if this team is over the team limit'''
done

2022-04-08 12:19 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                                (dsn['rateLimit']['window']))
Fair enough.

2022-04-08 12:20 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +            # @TODO use concurrent requests to scale out for tons of projects
I see that now for the second time. I actually kinda like the extra `@` in front of `TODO`, however, it would not be consistent to the other scripts.
Do you have something where you've got it from, that it was written with the `@`?

2022-04-08 12:20 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                print('WARNING: {} are configure of {} allowed for team: {}\
changed

2022-04-08 12:25 UTC, raimund-s commented on src/check_sentryio_limits.py
> +                                (dsn['rateLimit']['window']))
changed and adapted to daily rates

2022-04-08 12:26 UTC, raimund-s commented on src/check_sentryio_limits.py
> +    '''Check if global limit is reached'''
done

2022-04-08 12:30 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                                (dsn['rateLimit']['window']))
So much better! Thx! 👍🏼

2022-04-08 12:30 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +                print('WARNING: {} are configure, but {} allowed for team: {}'
```suggestion
                print('WARNING: {} are configured, but {} allowed for team: {}'
```

2022-04-08 12:30 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +            print('WARNING: {} events are configured, but {} allowd in total'
```suggestion
            print('WARNING: {} events are configured, but {} allowed in total'
```

2022-04-08 14:48 UTC, TheFRedFox commented on src/check_sentryio_limits.py
> +            print(f"\nTeam \"{team['name']}\", checking for projects")
That might be better to use with logging. But we will skip it for this PR.

2022-04-11 05:22 UTC, kofrezo requested changes
Just some minor improvements:
- Please check my comment about the magic number if we can improve that.
- Consider checking the HTTP status code if that makes sense.
- I consider the rest optional.

2022-04-11 05:22 UTC, kofrezo commented on src/check_sentryio_limits.py
> +                rate_daily = int(rate_count * 14400 / rate_window)
What is 14400 ?

It is best practise to avoid "magic numbers". Create a dedicated variable instead. For Example:
```
seconds_per_day = 60 * 60 * 24
```

2022-04-11 05:22 UTC, kofrezo commented on src/check_sentryio_limits.py
> +    return res.json()
```suggestion
    if res.status_code != 200:
        print(f'Expected HTTP 200 but got {res.status_code} while fetching dsns for project')
        sys.exit(3)  # Nagios code UNKNOWN

    return res.json()
```

2022-04-11 05:22 UTC, kofrezo commented on src/check_sentryio_limits.py
> +    return res.json()
```suggestion
    if res.status_code != 200:
        print(f'Expected HTTP 200 but got {res.status_code} while fetching teams')
        sys.exit(3)  # Nagios code UNKNOWN
        
     return res.json()
```

2022-04-11 05:22 UTC, kofrezo commented on src/check_sentryio_limits.py
> + - 1 (WARNING) Limits are either set to high or not at all
Let's not send some poor sysadmin debugging the script when there is network foo or the authentication failed.

I added to check for HTTP status code 200 further below.

```suggestion
 - 1 (WARNING) Limits are either set to high or not at all
 - 3 (UNKNOWN) Error while fetching team or project info via HTTP API
```

2022-04-11 14:55 UTC, kofrezo approved these changes

2022-04-11 15:11 UTC, merged