check_smartmon: Allow files starting with manufacturer name
innogames/igmonplugins pull request #263
Opened 2022-07-12 09:29 UTC by seqizz

New hardware has files starting directly with string INTEL

2022-08-10 08:56 UTC, TuxPowered42 requested changes

2022-08-10 08:56 UTC, TuxPowered42 commented on src/check_smartmon.py
> +    for csvfile in glob.glob(".*" + manufacturer + "*.csv"):
The change says allow files starting with manufacturer name, but the change is files starting with dot and any string and manufacturer name. This is supposed to be glob, not regexp.

2022-08-10 10:55 UTC, seqizz commented on src/check_smartmon.py
> +    for csvfile in glob.glob(".*" + manufacturer + "*.csv"):
Hmm, it doesn't act like glob though. In glob * means zero or more chars, which should've been OK in our case, but it is not :thinking:
I wonder if it is suddenly counting `./INTEL...` because of this change.
In any case, please advise, we need a change to grab strings starting with INTEL, and the current glob doesn't work for some reason.

2022-08-11 11:25 UTC, TuxPowered42 commented on src/check_smartmon.py
> +    for csvfile in glob.glob(".*" + manufacturer + "*.csv"):
```
[13:24:17] positron ~/ # mkdir test
[13:24:21] positron ~/ # cd test
[13:24:22] positron test/ # touch INTEL
[13:24:24] positron test/ # ls *INTEL
INTEL
[13:24:26] positron test/ # ls .*INTEL
zsh: no matches found: .*INTEL
[13:24:31] positron test/ # ls ./*INTEL
./INTEL
```

2022-08-11 12:13 UTC, closed without merging