check_zfs: Request explicit columns from zpool command
innogames/igmonplugins pull request #264
Opened 2022-07-12 09:39 UTC by seqizz

New version seems to be returning one more column, which we don't use and it breaks the check.

2022-07-12 13:59 UTC, TuxPowered42 requested changes

2022-07-12 13:59 UTC, TuxPowered42 commented on src/check_zfs.py
> +            '-o', 'name,size,alloc,free,expandsz,frag,cap,dedup,health,altroot'
Not all of those columns are needed. Look at parse_zpool():
```
name = data[0]
frag = data[5]
cap = data[6]
health = data[8]
```

We can clean up the code and get rid of unused parameters.

2022-07-12 14:14 UTC, seqizz commented on src/check_zfs.py
> +            '-o', 'name,size,alloc,free,expandsz,frag,cap,dedup,health,altroot'
Alright, pushed.

2022-08-08 11:05 UTC, TuxPowered42 approved these changes

2022-08-08 18:51 UTC, merged