Add check_secret for checking service restarts
innogames/igmonplugins pull request #272
Opened 2022-10-26 13:09 UTC by zados

check_secret checks if a service was restarted after secret rotation. The secret rotation is found in a timestamp file.

2022-10-26 13:12 UTC, TuxPowered42 commented on src/check_secret.py
> +        shell=True).decode("utf-8").split('=')[1].rstrip('\n')
Please don't run things with `shell=True`.

2022-10-26 13:17 UTC, TuxPowered42 commented on src/check_secret.py
> +        f"systemctl show {service_name}.service -p ExecMainStartTimestamp",
Please don't run things with shell=True.

2022-10-26 13:17 UTC, TuxPowered42 commented on src/check_secret.py
> +        shell=True).decode("utf-8").split('=')[1].rstrip('\n')
To get the value only use `--value`, then you don't need to strip.

2022-10-26 13:21 UTC, TuxPowered42 requested changes

2022-10-26 13:21 UTC, TuxPowered42 commented on src/check_secret.py
> +        f"systemctl show {service_name}.service -p ExecMainStartTimestamp",
Please don't run things with shell=True.

2022-10-26 13:21 UTC, TuxPowered42 commented on src/check_secret.py
> +        shell=True).decode("utf-8").split('=')[1].rstrip('\n')
To get the value only use --value, then you don't need to strip.

2022-10-27 11:13 UTC, kofrezo approved these changes
Early approve. Please decide for either double or single quotes and stick to one. I consider the description a nice to have.

2022-10-27 11:13 UTC, kofrezo commented on src/check_secret.py
> +    parser = ArgumentParser()
A description would be nice.

2022-10-27 11:13 UTC, kofrezo commented on src/check_secret.py
> +        ['/bin/systemctl', 'show', f"{service_name}.service", '-p',
No need for double quotes here. f-strings work with single quotes as well. Use either consistent.

2022-10-27 12:05 UTC, TuxPowered42 approved these changes

2022-10-27 12:48 UTC, merged