Add check_offline_cpus for offline CPU monitoring
innogames/igmonplugins pull request #275
Opened 2023-01-27 09:07 UTC by konstantinbest

For some years we have had the problem that sometimes some CPUs are offline after we have added them with igvm. The problem can sometimes be solved by manually setting the CPU to online, but it is often necessary to restart the VM.

Recently, we noticed that the CPU thread on the hypervisor has 100% load when the CPU is offline in the VM. 

This check allows us to find out which VMs are affected. This enables us to save CPU time on the affected hypervisors and to use all potential CPUs on the affected VMs.

2023-01-27 12:29 UTC, seqizz approved these changes
LGTM. I found a problematic host and a normal one to test both outputs.

2023-01-27 14:59 UTC, kofrezo requested changes
Please use sys.exit. I consider the other remarks debatable and IMHO style improvements. You may also consider using type hints.

2023-01-27 14:59 UTC, kofrezo commented on src/check_offline_cpus.py
> +def check_offline_cpus():
It's more `get_cpus(offline=True)` instead of `check` no ?

Nothing is checked but offline and total cpus are returned.

2023-01-27 14:59 UTC, kofrezo commented on src/check_offline_cpus.py
> +        "lscpu | grep '^CPU(s):' | awk '{print $2}'", shell=True
You rely on the PATH variable being set here. You could consider using the full path to each binary.

2023-01-27 14:59 UTC, kofrezo commented on src/check_offline_cpus.py
> +        print(f"OK - All {total_cpus} CPUs are online")
I wouldn't consider this a no-go but in line 49 you are already executing the function to get all CPUs (online and offline) but print them only down here. 

You could use two functions or a parameterized one and call them right before or in the print statement.

2023-01-27 14:59 UTC, kofrezo commented on src/check_offline_cpus.py
> +        exit(1)
Please use sys.exit see [Stackoverflow](https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python#:~:text=exit%20is%20a%20helper%20for,in%20namespace%20(e.g.%20exit%20).)

2023-01-27 14:59 UTC, kofrezo commented
Useful check btw!

2023-01-31 13:21 UTC, konstantinbest commented on src/check_offline_cpus.py
> +        "lscpu | grep '^CPU(s):' | awk '{print $2}'", shell=True
Relying on the PATH variable makes the code more readable and maintainable. By using the binary names instead of their full paths, the code is shorter, easier to understand, and less prone to breaking if the location of the executables changes

2023-01-31 13:22 UTC, konstantinbest commented on src/check_offline_cpus.py
> +        print(f"OK - All {total_cpus} CPUs are online")
I changed it a bit, please check if it is now better.

2023-02-01 13:16 UTC, kofrezo approved these changes

2023-02-13 09:42 UTC, merged

2023-02-13 09:44 UTC, TuxPowered42 commented on src/check_offline_cpus.py
> +        "lscpu | grep '^Off-line CPU(s) list:' | awk -F: '{print $2}'",
There's no need to use both grep and awk.

2023-02-13 09:44 UTC, TuxPowered42 commented on src/check_offline_cpus.py
> +        "lscpu | grep '^CPU(s):' | awk '{print $2}'",
There's no need to use both grep and awk.

2023-02-13 09:45 UTC, TuxPowered42 commented on src/check_offline_cpus.py
> +        "lscpu | grep '^Off-line CPU(s) list:' | awk -F: '{print $2}'",
To be honest there's no need to use shell for this at all. Handling such simple string splitting should be trivial in Python.