Add check for ambiguous apt package sources
innogames/igmonplugins pull request #301
Opened 2024-01-23 17:05 UTC by Woellchen

Monitoring script which checks that every known
package has only one available source to choose from

2024-01-23 17:21 UTC, TuxPowered42 requested changes

2024-01-23 17:21 UTC, TuxPowered42 commented on src/check_apt_ambiguous_source.py
> +SOURCE_REGEX = re.compile(r'^\s+[0-9]+\s(\S+\s\S+\s\S+\s\S+)$')
Please add an example of a line matched by this.

2024-01-23 17:21 UTC, TuxPowered42 commented on src/check_apt_ambiguous_source.py
> +    )
The exception should be caught and Nagios error code 3 should be returned.

2024-01-24 12:47 UTC, TuxPowered42 commented on src/check_apt_ambiguous_source.py
> +SOURCE_REGEX = re.compile(r'^\s+[0-9]+\s(\S+\s\S+\s\S+\s\S+)$')
Why parse text output instead of using the `apt` module?

```
import apt

for pkg in apt.cache.Cache():
    if not pkg.is_installed:
        continue
    print(f'Package: {pkg}')
    for origin in pkg.installed.origins:
        if origin.archive == 'now':
            continue
        print(f'    Source: {origin.site}/{origin.archive}')
```

2024-01-24 13:41 UTC, Woellchen commented on src/check_apt_ambiguous_source.py
> +SOURCE_REGEX = re.compile(r'^\s+[0-9]+\s(\S+\s\S+\s\S+\s\S+)$')
Because `python3-apt` pulls a lot of other dependencies into the mix and it would require future maintenance for breaking changes and possibly supporting multiple versions of it. I wanted a lightweight approach

2024-01-24 16:43 UTC, TuxPowered42 approved these changes

2024-01-24 16:49 UTC, merged